# Generated by Django 5.1.4 on 2024-12-29 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('conference_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('conference_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Conferences',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('season_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
            ],
            options={
                'db_table': 'Seasons',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_api.conference')),
            ],
            options={
                'db_table': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('stat_id', models.AutoField(primary_key=True, serialize=False)),
                ('average_offensive_rating', models.FloatField()),
                ('average_defensive_rating', models.FloatField()),
                ('average_net_rating', models.FloatField()),
                ('average_plus_minus', models.FloatField()),
                ('relative_net_rating', models.FloatField()),
                ('relative_offensive_rating', models.FloatField()),
                ('relative_defensive_rating', models.FloatField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_api.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba_api.team')),
            ],
            options={
                'db_table': 'TeamStats',
                'unique_together': {('team', 'season')},
            },
        ),
    ]
